CREATE FUNCTION FaturamentoNota (@NUMERO AS INT)
RETURNS FLOAT
AS
BEGIN
	DECLARE @FATURAMENTO FLOAT 
	SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO])
	FROM [dbo].[ITENS NOTAS FISCAIS]
	where NUMERO = @NUMERO
	RETURN @FATURAMENTO
END;


SELECT NUMERO, dbo.FaturamentoNota(NUMERO) AS FATURAMENTO
FROM [dbo].[NOTAS FISCAIS]

select * from [ITENS NOTAS FISCAIS]