DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT
DECLARE @TABELA_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR(200), [FATURAMENTO] FLOAT)
DECLARE @CONTADOR_NOTAS INT

--SET @LIMITE_MINIMO = 1
--SET @LIMITE_MAXIMO = 100000

    IF @CONTADOR_NOTAS > 0
        BEGIN
            INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS, FATURAMENTO)
            VALUES (@LIMITE_MINIMO, 'É NOTA FISCAL', [dbo].[FaturamentoNota](@LIMITE_MINIMO))
        END
    ELSE
        BEGIN
            INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS, FATURAMENTO)
            VALUES (@LIMITE_MINIMO, 'NÃO É NOTA FISCAL', 0)
        END

		SELECT dbo.FaturamentoNota(5000)
