--SELECT DISTINCT SABOR FROM [TABELA DE PRODUTOS]

--SELECT * FROM [TABELA DE PRODUTOS]
CREATE PROCEDURE TESTE
 @DATA AS DATETIME, @DEPARTAMENTO AS VARCHAR (150) 
 AS 
 BEGIN
SELECT

@DEPARTAMENTO	= CASE TP.SABOR
					WHEN 'LARANJA'	THEN 'FRUTAS CÍTRICAS'
					WHEN 'LIMA/LIMÃO' THEN 'FRUTAS CÍTRICAS'
					ELSE 'FRUTAS NÃO CÍTRICAS'
	     		  END
		FROM [TABELA DE PRODUTOS] TP
	JOIN [ITENS NOTAS FISCAIS] INF
		ON INF.[CODIGO DO PRODUTO]=INF.[CODIGO DO PRODUTO]
	JOIN [NOTAS FISCAIS] NF
		ON NF.NUMERO=NF.NUMERO
	WHERE TP.SABOR = @DEPARTAMENTO AND NF.DATA = @DATA
END

EXEC TESTE
DECLARE  @DATA DATE
DECLARE @DEPARTAMENTO  VARCHAR (150)

SET @DATA = NULL 
SET @DEPARTAMENTO = 0
SELECT @DEPARTAMENTO,
	   @DATA
	  FROM [TABELA DE PRODUTOS] TP
	JOIN [ITENS NOTAS FISCAIS] INF
		ON INF.[CODIGO DO PRODUTO]=INF.[CODIGO DO PRODUTO]
	JOIN [NOTAS FISCAIS] NF
		ON NF.NUMERO=NF.NUMERO
	WHERE TP.SABOR = @DEPARTAMENTO AND NF.DATA = @DATA
